# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"!\n\x0e\x43hannelRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2w\n\tMessenger\x12\x33\n\x0eReceiveMessage\x12\x0f.ChannelRequest\x1a\x10.MessageResponse\x12\x35\n\x0eStreamMessages\x12\x0f.ChannelRequest\x1a\x10.MessageResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELREQUEST']._serialized_start=17
  _globals['_CHANNELREQUEST']._serialized_end=50
  _globals['_MESSAGERESPONSE']._serialized_start=52
  _globals['_MESSAGERESPONSE']._serialized_end=86
  _globals['_MESSENGER']._serialized_start=88
  _globals['_MESSENGER']._serialized_end=207
# @@protoc_insertion_point(module_scope)
